[package]
name = "tikv_alloc"
version = "0.1.0"
edition = "2018"
authors = ["Brian Anderson <andersrb@gmail.com>"]
publish = false

[features]
default = ["jemalloc"]
jemalloc = ["jemallocator", "jemalloc-sys", "jemalloc-ctl"]

# Build jemalloc's profiling features. Without this
# certain profile functions will return nothing.
mem-profiling = ["jemallocator/profiling"]

[dependencies]
libc = "0.2"
log = "0.3"
quick-error = "1.2.2"

[dev-dependencies]
tempdir = "0.3"

# FIXME: Shouldn't need to depend on the git repos but jemalloc-ctl 0.3
# isn't published.
#
# https://github.com/gnzlbg/jemallocator/issues/113

[dependencies.jemallocator]
version = "0.3.0"
optional = true
features = ["stats", "unprefixed_malloc_on_supported_platforms"]
git = "https://github.com/gnzlbg/jemallocator.git"
rev = "522c032dc394524ae6b7a5b0661ba879bd960f7c"

[dependencies.jemalloc-sys]
version = "0.3.0"
optional = true
git = "https://github.com/gnzlbg/jemallocator.git"
rev = "522c032dc394524ae6b7a5b0661ba879bd960f7c"

[dependencies.jemalloc-ctl]
version = "0.3.0"
optional = true
git = "https://github.com/gnzlbg/jemallocator.git"
rev = "522c032dc394524ae6b7a5b0661ba879bd960f7c"

[dependencies.tcmalloc]
version = "0.3.0"
optional = true
features = ["bundled"]
