[package]
name = "fuzz-targets"
version = "0.0.1"
publish = false
edition = "2018"

[lib]
path = "mod.rs"
test = false
bench = false
doctest = false

[dependencies]
byteorder = "1"
failure = "0.1"
tikv_util = { path = "../../components/tikv_util" }
tikv = {path = "../..", default-features = false}
