[package]
name = "tikv_misc"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
engine = { path = "../engine" }
grpcio = { version = "0.4" }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
protobuf = "~2.0"
quick-error = "1.2.2"
raft = "0.4"
slog = { version = "2.3" }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
tikv_util = { path = "../tikv_util" }
time = "0.1"
