[package]
name = "pd"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
lazy_static = "0.2.1"
grpcio = { version = "0.4", features = [ "secure" ] }
quick-error = "1.2.2"
protobuf = "~2.0"
raft = "0.4"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3" }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
tikv_alloc = { path = "../tikv_alloc", default-features = false }
tikv_util = { path = "../tikv_util" }
tikv_misc = { path = "../tikv_misc" }
tokio-timer = "0.2"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]
